import assert from "node:assert/strict";
import test from "node:test";
import { MAX_FRAME_BYTES, MAX_FRAME_SEQUENCE, RuntimeTransportModelError, acceptFrame, advanceEpoch, cancelTransport, createTransportState, frameFor, validateTransportState } from "../guard-host/runtime-transport-model.ts";
const nonce = "a".repeat(32);

test("transport state and frames are bounded and non-authenticating", () => { const s = createTransportState(nonce), f = frameFor(s, "request", "synthetic"); assert.equal(MAX_FRAME_BYTES, 8192); assert.equal(MAX_FRAME_SEQUENCE, 64); assert.equal(f.epoch, 0); assert.equal(f.sequence, 0); assert.equal((s as any).authenticated, undefined); });
test("frames require exact nonce, epoch and next sequence", () => { let s = createTransportState(nonce); s = acceptFrame(s, frameFor(s, "request", "one")); assert.equal(s.nextSequence, 1); s = acceptFrame(s, frameFor(s, "response", "two")); assert.deepEqual(s.accepted, [0, 1]); });
test("duplicate, out-of-order, stale and wrong-nonce frames fail closed", () => { let s = createTransportState(nonce); const first = frameFor(s, "request", "one"); s = acceptFrame(s, first); for (const bad of [first, { ...first, sequence: 3 }, { ...first, nonce: "b".repeat(32) }, { ...first, epoch: 1 }]) assert.throws(() => acceptFrame(s, bad as never), RuntimeTransportModelError); });
test("cancellation rejects new frames and preserves prior accepted evidence", () => { let s = acceptFrame(createTransportState(nonce), frameFor(createTransportState(nonce), "request", "one")); s = cancelTransport(s); assert.equal(s.cancelled, true); assert.deepEqual(s.accepted, [0]); assert.throws(() => frameFor(s, "cancel", "late"), RuntimeTransportModelError); });
test("epoch advance resets sequence only after a quiescent state", () => { let s = createTransportState(nonce); s = acceptFrame(s, frameFor(s, "request", "one")); const next = advanceEpoch(s); assert.equal(next.epoch, 1); assert.equal(next.nextSequence, 0); assert.deepEqual(next.accepted, []); });
test("oversized, malformed and extra-field frames fail closed", () => { const s = createTransportState(nonce); for (const bad of [{ ...frameFor(s, "request", "x"), extra: true }, { ...frameFor(s, "request", "x"), body: "x".repeat(MAX_FRAME_BYTES + 1) }, { ...frameFor(s, "request", "x"), version: 2 }, null, []]) assert.throws(() => acceptFrame(s, bad as never), RuntimeTransportModelError); });
test("state validation rejects gaps, duplicates, negative and oversized sequence state", () => { const s = createTransportState(nonce); for (const bad of [{ ...s, accepted: [1], nextSequence: 1 }, { ...s, accepted: [0, 0], nextSequence: 2 }, { ...s, nextSequence: -1 }, { ...s, nextSequence: MAX_FRAME_SEQUENCE + 1 }]) assert.throws(() => validateTransportState(bad), RuntimeTransportModelError); });
test("epoch cannot advance from inconsistent accepted state", () => { const s = { ...createTransportState(nonce), nextSequence: 1 }; assert.throws(() => advanceEpoch(s), RuntimeTransportModelError); });
test("returned frame/state arrays are detached and late epoch frames remain invalid", () => { let s = createTransportState(nonce); const f = frameFor(s, "request", "x"); const accepted = acceptFrame(s, f); (accepted.accepted as number[]).push(9); assert.deepEqual(s.accepted, []); const next = advanceEpoch(acceptFrame(s, f)); assert.throws(() => acceptFrame(next, f), RuntimeTransportModelError); });
test("transport model never grants execution, peer or recovery authority", () => { const s = createTransportState(nonce); const f = frameFor(s, "cancel", "stop"); assert.equal((f as any).authorized, undefined); assert.equal((s as any).peerPid, undefined); assert.equal((s as any).recovery, undefined); });
