import assert from "node:assert/strict";
import test from "node:test";
import { MAX_MESSAGES, MAX_SUMMARY_BYTES, SessionCompactionModelError, acceptCompaction, advancePolicy, createSessionBoundary, proposeCompaction, validateCompactionBoundary } from "../guard-host/session-compaction-model.ts";
const summary = "Retained synthetic context only.";

test("compaction boundary is fixed, bounded and non-executable", () => { const s = createSessionBoundary(); assert.equal(s.sessionId, "session-0000000000000000"); assert.equal(s.workspace, "workspace-00000000"); assert.equal(MAX_MESSAGES, 128); assert.equal(MAX_SUMMARY_BYTES, 16384); });
test("proposal binds session, workspace and policy epoch", () => { const s = createSessionBoundary(), p = proposeCompaction(s, summary, ["PHI_SYNTHETIC_USER"]); assert.equal(p.executable, false); assert.deepEqual(p.retained, ["PHI_SYNTHETIC_USER"]); });
test("accepted compaction preserves identity and copies retained messages", () => { const s = createSessionBoundary(), p = proposeCompaction(s, summary, s.messages), next = acceptCompaction(s, p); assert.equal(next.sessionId, s.sessionId); assert.equal(next.workspace, s.workspace); assert.equal(next.policyEpoch, s.policyEpoch); assert.deepEqual(next.messages, s.messages); assert.notEqual(next.messages, s.messages); });
test("policy change rejects an older compaction proposal", () => { const s = createSessionBoundary(), p = proposeCompaction(s, summary, s.messages), next = advancePolicy(s); assert.throws(() => acceptCompaction(next, p), SessionCompactionModelError); });
test("workspace/session mismatch cannot apply a summary", () => { const s = createSessionBoundary(), p = proposeCompaction(s, summary, s.messages); for (const bad of [{ ...p, sessionId: "session-1111111111111111" }, { ...p, workspace: "workspace-11111111" }, { ...p, executable: true }]) assert.throws(() => acceptCompaction(s, bad as never), SessionCompactionModelError); });
test("summary cannot become a launch, credential or host-data channel", () => { const s = createSessionBoundary(); for (const text of ["execute command", "launch agent", "Docker socket", "host path C:\\private", "credential token", "SYNTHETIC_SECRET_NOT_A_CREDENTIAL"]) assert.throws(() => proposeCompaction(s, text, s.messages), SessionCompactionModelError); });
test("oversized, empty and unretained summaries fail closed", () => { const s = createSessionBoundary(); for (const text of ["", "x".repeat(MAX_SUMMARY_BYTES + 1)]) assert.throws(() => proposeCompaction(s, text, s.messages), SessionCompactionModelError); assert.throws(() => proposeCompaction(s, summary, ["not-retained"]), SessionCompactionModelError); });
test("message and retention bounds are enforced", () => { const s = createSessionBoundary(); assert.throws(() => validateCompactionBoundary({ ...s, messages: Array(MAX_MESSAGES + 1).fill("x") }), SessionCompactionModelError); assert.throws(() => proposeCompaction(s, summary, Array(MAX_MESSAGES + 1).fill("x")), SessionCompactionModelError); });
test("malformed boundary identity and policy values fail closed", () => { const s = createSessionBoundary(); for (const bad of [{ ...s, sessionId: "../private" }, { ...s, workspace: "C:\\private" }, { ...s, policyEpoch: -1 }, { ...s, policyEpoch: 1.2 }]) assert.throws(() => validateCompactionBoundary(bad), SessionCompactionModelError); });
test("summary and proposal mutations do not alter the source boundary", () => { const s = createSessionBoundary(), p = proposeCompaction(s, summary, s.messages); const retained = p.retained as string[]; retained.push("mutated"); assert.deepEqual(s.messages, ["PHI_SYNTHETIC_USER"]); assert.equal(s.summary, undefined); });
