// Pure framed-transport model. It does not open a pipe/socket or authenticate a peer.
export const MAX_FRAME_BYTES = 8192;
export const MAX_FRAME_SEQUENCE = 64;
export interface TransportFrame { readonly version: 1; readonly nonce: string; readonly epoch: number; readonly sequence: number; readonly kind: "request" | "response" | "cancel"; readonly body: string; }
export interface TransportState { readonly nonce: string; readonly epoch: number; readonly nextSequence: number; readonly cancelled: boolean; readonly accepted: readonly number[]; }
export class RuntimeTransportModelError extends Error { readonly rule = "RUNTIME_TRANSPORT_MODEL_INVALID"; constructor() { super("RUNTIME_TRANSPORT_MODEL_INVALID"); } }
function validFrame(f: TransportFrame): void { if (!f || typeof f !== "object" || Object.keys(f).sort().join(",") !== "body,epoch,kind,nonce,sequence,version" || f.version !== 1 || !/^[a-f0-9]{32}$/.test(f.nonce) || !Number.isSafeInteger(f.epoch) || f.epoch < 0 || !Number.isSafeInteger(f.sequence) || f.sequence < 0 || f.sequence >= MAX_FRAME_SEQUENCE || !["request", "response", "cancel"].includes(f.kind) || typeof f.body !== "string" || Buffer.byteLength(f.body) > MAX_FRAME_BYTES) throw new RuntimeTransportModelError(); }
export function createTransportState(nonce = "a".repeat(32)): TransportState { if (!/^[a-f0-9]{32}$/.test(nonce)) throw new RuntimeTransportModelError(); return { nonce, epoch: 0, nextSequence: 0, cancelled: false, accepted: [] }; }
export function frameFor(s: TransportState, kind: TransportFrame["kind"], body: string): TransportFrame { if (s.cancelled || typeof body !== "string" || Buffer.byteLength(body) > MAX_FRAME_BYTES || s.nextSequence >= MAX_FRAME_SEQUENCE) throw new RuntimeTransportModelError(); const f = { version: 1 as const, nonce: s.nonce, epoch: s.epoch, sequence: s.nextSequence, kind, body }; validFrame(f); return f; }
export function acceptFrame(s: TransportState, f: TransportFrame): TransportState { validFrame(f); if (s.cancelled || f.nonce !== s.nonce || f.epoch !== s.epoch || f.sequence !== s.nextSequence || s.accepted.includes(f.sequence)) throw new RuntimeTransportModelError(); return { ...s, nextSequence: s.nextSequence + 1, accepted: [...s.accepted, f.sequence] }; }
export function cancelTransport(s: TransportState): TransportState { if (s.cancelled) throw new RuntimeTransportModelError(); return { ...s, cancelled: true, accepted: [...s.accepted] }; }
export function advanceEpoch(s: TransportState): TransportState { if (s.accepted.length !== s.nextSequence) throw new RuntimeTransportModelError(); return { ...s, epoch: s.epoch + 1, nextSequence: 0, accepted: [], cancelled: false }; }
export function validateTransportState(s: TransportState): void { if (!s || !/^[a-f0-9]{32}$/.test(s.nonce) || !Number.isSafeInteger(s.epoch) || s.epoch < 0 || !Number.isSafeInteger(s.nextSequence) || s.nextSequence < 0 || s.nextSequence > MAX_FRAME_SEQUENCE || s.accepted.length !== s.nextSequence || new Set(s.accepted).size !== s.accepted.length || s.accepted.some((n, i) => n !== i)) throw new RuntimeTransportModelError(); }
